// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcZfE3Yo4caE5LCqTDbh4KSMZAM3qiRY8',
    appId: '1:484197049849:web:2f9f74655fd2dbf2024928',
    messagingSenderId: '484197049849',
    projectId: 'jobsheets-23a93',
    authDomain: 'jobsheets-23a93.firebaseapp.com',
    storageBucket: 'jobsheets-23a93.appspot.com',
    measurementId: 'G-2EV7X28HXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxNXGfkjiw9gmVq3VpfGBwhUiqzMUJyNs',
    appId: '1:484197049849:android:4f4dac402786e3fc024928',
    messagingSenderId: '484197049849',
    projectId: 'jobsheets-23a93',
    storageBucket: 'jobsheets-23a93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWBaZy_tLHqNzW9t2CUnyMHxkK3SzeRmg',
    appId: '1:484197049849:ios:b1ea2fa6834f15c6024928',
    messagingSenderId: '484197049849',
    projectId: 'jobsheets-23a93',
    storageBucket: 'jobsheets-23a93.appspot.com',
    iosClientId: '484197049849-qdd9ftmiqcre62dhba1urci0fprvpjfu.apps.googleusercontent.com',
    iosBundleId: 'com.example.atmega1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWBaZy_tLHqNzW9t2CUnyMHxkK3SzeRmg',
    appId: '1:484197049849:ios:b1ea2fa6834f15c6024928',
    messagingSenderId: '484197049849',
    projectId: 'jobsheets-23a93',
    storageBucket: 'jobsheets-23a93.appspot.com',
    iosClientId: '484197049849-qdd9ftmiqcre62dhba1urci0fprvpjfu.apps.googleusercontent.com',
    iosBundleId: 'com.example.atmega1',
  );
}
